[Interface]
Address = 10.99.0.1/24
ListenPort = 51820
PrivateKey = qPiTZJYig6vtMe8IV799PJrj+JmPQ6kqhk6vEdWnEns=

[Peer]
# Homelab (backend server)
PublicKey = AdZG7G7cwaYTIUB9CyF2FxxwQWUyQLab+VWIkM9rMEI=
AllowedIPs = 10.99.0.3/32
Endpoint = 176.141.9.146:51820
PersistentKeepalive = 5
