"""PlanCandidate dataclass — represents a single plan candidate with cost/quality metadata.

Includes a ``predicted_strategy`` field populated by the calibration module
so consumers can see which execution strategy this plan would likely use.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .calibration import predict_strategy


@dataclass(slots=True)
class PlanCandidate:
    """A single plan candidate generated by one strategy.

    Attributes:
        plan_id: Unique identifier for this candidate
            (e.g. ``"heuristic_v1"``, ``"llm_persona_a"``).
        generation_strategy: One of ``"heuristic"``, ``"llm_persona"``,
            ``"llm_default"``.
        tasks: Serialized ``MissionTask`` list (list of dicts with keys
            ``title``, ``description``, ``task_type``, ``dependencies``).
        estimated_cost_usd: Estimated cost in USD from the cost model.
        estimated_latency_ms: Estimated wall-clock latency in milliseconds.
        estimated_tokens: Estimated total tokens (prompt + completion).
        quality_score: Heuristic quality score in [0.0, 1.0].
        risk_flags: List of risk flag strings (e.g. ``"unbounded_retry"``).
        rationale: Human-readable explanation of how this plan differs.
    """

    plan_id: str
    generation_strategy: str  # "heuristic" | "llm_persona" | "llm_default"
    tasks: list[dict]
    estimated_cost_usd: float = 0.0
    estimated_latency_ms: int = 0
    estimated_tokens: int = 0
    quality_score: float = 0.0
    risk_flags: list[str] = field(default_factory=list)
    rationale: str = ""
    predicted_strategy: str = ""  # execution strategy predicted by calibration

    def __post_init__(self) -> None:
        """Auto-populate predicted_strategy if not set."""
        if not self.predicted_strategy:
            self.predicted_strategy = predict_strategy(self.tasks)

    def to_dict(self) -> dict:
        """Serialize to a plain dict for JSONB storage."""
        return {
            "plan_id": self.plan_id,
            "generation_strategy": self.generation_strategy,
            "tasks": self.tasks,
            "estimated_cost_usd": self.estimated_cost_usd,
            "estimated_latency_ms": self.estimated_latency_ms,
            "estimated_tokens": self.estimated_tokens,
            "quality_score": self.quality_score,
            "risk_flags": self.risk_flags,
            "rationale": self.rationale,
            "predicted_strategy": self.predicted_strategy,
        }

    @classmethod
    def from_dict(cls, data: dict) -> PlanCandidate:
        """Deserialize from a plain dict."""
        return cls(
            plan_id=data["plan_id"],
            generation_strategy=data["generation_strategy"],
            tasks=data["tasks"],
            estimated_cost_usd=data.get("estimated_cost_usd", 0.0),
            estimated_latency_ms=data.get("estimated_latency_ms", 0),
            estimated_tokens=data.get("estimated_tokens", 0),
            quality_score=data.get("quality_score", 0.0),
            risk_flags=data.get("risk_flags", []),
            rationale=data.get("rationale", ""),
            predicted_strategy=data.get("predicted_strategy", ""),
        )
