"""
Add agent registry models

Revision ID: 2026_02_01_1300
Revises: 2026_02_01_1200_add_agent_model_preferences
Create Date: 2026-02-01 13:00:00.000000

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '2026_02_01_1300'
down_revision = '2026_02_01_1200_add_agent_model_preferences'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create agent_capabilities table
    op.create_table('agent_capabilities',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('capability_name', sa.String(length=255), nullable=False),
        sa.Column('category', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('required_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('performance_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('version', sa.String(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('capability_name')
    )
    
    # Create indexes for agent_capabilities
    op.create_index('idx_agent_capabilities_name', 'agent_capabilities', ['capability_name'], unique=False)
    op.create_index('idx_agent_capabilities_category', 'agent_capabilities', ['category'], unique=False)
    op.create_index('idx_agent_capabilities_active', 'agent_capabilities', ['is_active'], unique=False)
    
    # Create agent_instances table
    op.create_table('agent_instances',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('instance_id', sa.String(length=255), nullable=False),
        sa.Column('agent_template_id', sa.Integer(), nullable=True),
        sa.Column('agent_name', sa.String(length=255), nullable=False),
        sa.Column('agent_type', sa.String(length=100), nullable=False),
        sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('capability_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('health_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('endpoint_url', sa.String(length=500), nullable=True),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
        sa.Column('registered_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['agent_template_id'], ['agent_templates.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('instance_id')
    )
    
    # Create indexes for agent_instances
    op.create_index('idx_agent_instances_instance_id', 'agent_instances', ['instance_id'], unique=False)
    op.create_index('idx_agent_instances_type', 'agent_instances', ['agent_type'], unique=False)
    op.create_index('idx_agent_instances_status', 'agent_instances', ['status'], unique=False)
    op.create_index('idx_agent_instances_heartbeat', 'agent_instances', ['last_heartbeat_at'], unique=False)
    op.create_index('idx_agent_instances_template', 'agent_instances', ['agent_template_id'], unique=False)
    
    # Create agent_performance_metrics table
    op.create_table('agent_performance_metrics',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('instance_id', sa.String(length=255), nullable=False),
        sa.Column('metric_type', sa.String(length=50), nullable=False),
        sa.Column('capability', sa.String(length=255), nullable=True),
        sa.Column('value', sa.Float(), nullable=False),
        sa.Column('unit', sa.String(length=50), nullable=True),
        sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('recorded_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['instance_id'], ['agent_instances.instance_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for agent_performance_metrics
    op.create_index('idx_agent_perf_metrics_instance', 'agent_performance_metrics', ['instance_id'], unique=False)
    op.create_index('idx_agent_perf_metrics_type', 'agent_performance_metrics', ['metric_type'], unique=False)
    op.create_index('idx_agent_perf_metrics_capability', 'agent_performance_metrics', ['capability'], unique=False)
    op.create_index('idx_agent_perf_metrics_recorded', 'agent_performance_metrics', ['recorded_at'], unique=False)
    
    # ### end Alembic commands ###
    
    # Seed initial capabilities
    seed_capabilities(op)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_agent_perf_metrics_recorded', table_name='agent_performance_metrics')
    op.drop_index('idx_agent_perf_metrics_capability', table_name='agent_performance_metrics')
    op.drop_index('idx_agent_perf_metrics_type', table_name='agent_performance_metrics')
    op.drop_index('idx_agent_perf_metrics_instance', table_name='agent_performance_metrics')
    op.drop_table('agent_performance_metrics')
    
    op.drop_index('idx_agent_instances_template', table_name='agent_instances')
    op.drop_index('idx_agent_instances_heartbeat', table_name='agent_instances')
    op.drop_index('idx_agent_instances_status', table_name='agent_instances')
    op.drop_index('idx_agent_instances_type', table_name='agent_instances')
    op.drop_index('idx_agent_instances_instance_id', table_name='agent_instances')
    op.drop_table('agent_instances')
    
    op.drop_index('idx_agent_capabilities_active', table_name='agent_capabilities')
    op.drop_index('idx_agent_capabilities_category', table_name='agent_capabilities')
    op.drop_index('idx_agent_capabilities_name', table_name='agent_capabilities')
    op.drop_table('agent_capabilities')
    # ### end Alembic commands ###


def seed_capabilities(op):
    """Seed initial capabilities into the database."""
    capabilities = [
        {
            'capability_name': 'code_generation',
            'category': 'coding',
            'description': 'Generate code in various programming languages',
            'required_parameters': {'required': ['language', 'task']},
            'performance_metrics': {'expected_latency_ms': 2000, 'accuracy_threshold': 0.8},
            'version': '1.0.0'
        },
        {
            'capability_name': 'data_analysis',
            'category': 'analytics',
            'description': 'Analyze data and provide insights',
            'required_parameters': {'required': ['data_source']},
            'performance_metrics': {'expected_latency_ms': 5000, 'accuracy_threshold': 0.9},
            'version': '1.0.0'
        },
        {
            'capability_name': 'image_generation',
            'category': 'vision',
            'description': 'Generate images from text descriptions',
            'required_parameters': {'required': ['prompt']},
            'performance_metrics': {'expected_latency_ms': 10000, 'quality_threshold': 0.7},
            'version': '1.0.0'
        },
        {
            'capability_name': 'text_summarization',
            'category': 'nlp',
            'description': 'Summarize long text into concise versions',
            'required_parameters': {'required': ['text']},
            'performance_metrics': {'expected_latency_ms': 1000, 'compression_ratio': 0.3},
            'version': '1.0.0'
        },
        {
            'capability_name': 'question_answering',
            'category': 'nlp',
            'description': 'Answer questions based on provided context',
            'required_parameters': {'required': ['question', 'context']},
            'performance_metrics': {'expected_latency_ms': 1500, 'accuracy_threshold': 0.85},
            'version': '1.0.0'
        },
        {
            'capability_name': 'reasoning',
            'category': 'cognitive',
            'description': 'Perform logical reasoning and inference',
            'required_parameters': {'required': ['problem']},
            'performance_metrics': {'expected_latency_ms': 3000, 'accuracy_threshold': 0.9},
            'version': '1.0.0'
        },
        {
            'capability_name': 'planning',
            'category': 'cognitive',
            'description': 'Create plans and strategies for complex tasks',
            'required_parameters': {'required': ['goal', 'constraints']},
            'performance_metrics': {'expected_latency_ms': 4000, 'completeness_threshold': 0.8},
            'version': '1.0.0'
        }
    ]
    
    for cap in capabilities:
        op.execute(
            sa.text("""
                INSERT INTO agent_capabilities 
                (id, capability_name, category, description, required_parameters, performance_metrics, version, is_active, created_at, updated_at)
                VALUES 
                (gen_random_uuid(), :capability_name, :category, :description, :required_parameters, :performance_metrics, :version, true, NOW(), NOW())
                ON CONFLICT (capability_name) DO NOTHING
            """),
            {
                'capability_name': cap['capability_name'],
                'category': cap['category'],
                'description': cap['description'],
                'required_parameters': json.dumps(cap['required_parameters']),
                'performance_metrics': json.dumps(cap['performance_metrics']),
                'version': cap['version']
            }
        )


import json
