# mypy: disable-error-code=attr-defined
"""
Add agent model preferences and cost tracking

Revision ID: 2026_02_01_1200
Revises: 2026_01_30_1000
Create Date: 2026-02-01 12:00:00.000000
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "2026_02_01_1200"
down_revision = "2026_01_30_1000"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add columns to agent_profiles table
    op.add_column(
        "agent_profiles",
        sa.Column(
            "preferred_models",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            default=list,
        ),
    )
    op.add_column(
        "agent_profiles",
        sa.Column(
            "model_selection_strategy",
            sa.String(length=50),
            nullable=True,
            default="balanced",
        ),
    )
    op.add_column(
        "agent_profiles",
        sa.Column(
            "model_performance_history",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            default=dict,
        ),
    )
    op.add_column(
        "agent_profiles",
        sa.Column("daily_cost_budget", sa.Float(), nullable=True, default=0.1),
    )
    op.add_column(
        "agent_profiles",
        sa.Column("monthly_cost_budget", sa.Float(), nullable=True, default=1.0),
    )

    # Create index on model_selection_strategy
    op.create_index(
        "idx_agent_profile_model_strategy",
        "agent_profiles",
        ["model_selection_strategy"],
        unique=False,
    )

    # Add columns to swarm_agents table
    op.add_column(
        "swarm_agents",
        sa.Column("assigned_model", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "swarm_agents",
        sa.Column(
            "model_fallback_chain",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            default=list,
        ),
    )
    op.add_column(
        "swarm_agents",
        sa.Column(
            "cost_tracking",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            default=dict,
        ),
    )
    op.add_column(
        "swarm_agents",
        sa.Column("model_switch_count", sa.Integer(), nullable=True, default=0),
    )

    # Create index on assigned_model
    op.create_index(
        "idx_swarm_agent_assigned_model",
        "swarm_agents",
        ["assigned_model"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop columns from agent_profiles
    op.drop_index("idx_agent_profile_model_strategy", table_name="agent_profiles")
    op.drop_column("agent_profiles", "preferred_models")
    op.drop_column("agent_profiles", "model_selection_strategy")
    op.drop_column("agent_profiles", "model_performance_history")
    op.drop_column("agent_profiles", "daily_cost_budget")
    op.drop_column("agent_profiles", "monthly_cost_budget")

    # Drop columns from swarm_agents
    op.drop_index("idx_swarm_agent_assigned_model", table_name="swarm_agents")
    op.drop_column("swarm_agents", "assigned_model")
    op.drop_column("swarm_agents", "model_fallback_chain")
    op.drop_column("swarm_agents", "cost_tracking")
    op.drop_column("swarm_agents", "model_switch_count")

    # ### end Alembic commands ###
