"""Add swarm system models and extend agent_communications

Revision ID: 2026_01_30_1000_add_swarm_models
Revises: 2026_01_11_1905-add-blacklisted-tokens
Create Date: 2026-01-30 10:00:00.000000

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "2026_01_30_1000_add_swarm_models"
down_revision = "2026_01_11_1905_add_blacklisted_tokens"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create litellm_audit_log table
    op.create_table(
        "litellm_audit_log",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), default=dict),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_litellm_audit_user"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_litellm_audit_log"),
    )
    op.create_index("idx_litellm_audit_user", "litellm_audit_log", ["user_id"])
    op.create_index("idx_litellm_audit_action", "litellm_audit_log", ["action"])
    op.create_index("idx_litellm_audit_created", "litellm_audit_log", ["created_at"])

    # 2. Create agent_templates table
    op.create_table(
        "agent_templates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("template_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column(
            "capabilities", postgresql.JSONB(astext_type=sa.Text()), server_default="[]"
        ),
        sa.Column(
            "default_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
        ),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("icon_url", sa.String(length=500), nullable=True),
        sa.Column("rating_avg", sa.Float(), server_default="0.0"),
        sa.Column("rating_count", sa.Integer(), server_default="0"),
        sa.Column("usage_count", sa.Integer(), server_default="0"),
        sa.Column("is_active", sa.Boolean(), server_default="true"),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="pk_agent_templates"),
        sa.UniqueConstraint("template_id", name="uq_agent_templates_template_id"),
    )
    op.create_index("idx_agent_templates_category", "agent_templates", ["category"])
    op.create_index("idx_agent_templates_rating", "agent_templates", ["rating_avg"])

    # 3. Create swarm_profiles table
    op.create_table(
        "swarm_profiles",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("swarm_id", sa.String(length=255), nullable=False),
        sa.Column("swarm_name", sa.String(length=255), nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=True),
        sa.Column("consensus_strategy", sa.String(length=50), nullable=True),
        sa.Column(
            "consensus_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
        ),
        sa.Column("status", sa.String(length=50), server_default="active"),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=True
        ),
        sa.Column("dissolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="fk_swarm_profiles_user"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_swarm_profiles"),
        sa.UniqueConstraint("swarm_id", name="uq_swarm_profiles_swarm_id"),
    )
    op.create_index("idx_swarm_status", "swarm_profiles", ["status"])
    op.create_index("idx_swarm_created_by", "swarm_profiles", ["created_by"])

    # 4. Create swarm_agents table
    op.create_table(
        "swarm_agents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("swarm_id", sa.String(length=255), nullable=False),
        sa.Column("agent_template_id", sa.Integer(), nullable=True),
        sa.Column("agent_instance_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=True),
        sa.Column("priority", sa.Integer(), server_default="5"),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}"
        ),
        sa.Column("status", sa.String(length=50), server_default="active"),
        sa.Column(
            "joined_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=True
        ),
        sa.Column(
            "last_active_at",
            sa.DateTime(),
            server_default=sa.text("NOW()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["swarm_id"],
            ["swarm_profiles.swarm_id"],
            ondelete="CASCADE",
            name="fk_swarm_agents_swarm",
        ),
        sa.ForeignKeyConstraint(
            ["agent_template_id"],
            ["agent_templates.id"],
            name="fk_swarm_agents_template",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_swarm_agents"),
        sa.UniqueConstraint("agent_instance_id", name="uq_swarm_agents_instance_id"),
    )
    op.create_index("idx_swarm_agents_swarm", "swarm_agents", ["swarm_id"])
    op.create_index("idx_swarm_agents_status", "swarm_agents", ["status"])

    # 5. Create swarm_tasks table
    op.create_table(
        "swarm_tasks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("swarm_id", sa.String(length=255), nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}"
        ),
        sa.Column("status", sa.String(length=50), server_default="pending"),
        sa.Column("assigned_agent_id", sa.String(length=255), nullable=True),
        sa.Column("celery_task_id", sa.String(length=255), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=True
        ),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["swarm_id"],
            ["swarm_profiles.swarm_id"],
            ondelete="CASCADE",
            name="fk_swarm_tasks_swarm",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_swarm_tasks"),
    )
    op.create_index("idx_swarm_tasks_swarm", "swarm_tasks", ["swarm_id"])
    op.create_index("idx_swarm_tasks_status", "swarm_tasks", ["status"])
    op.create_index("idx_swarm_tasks_celery", "swarm_tasks", ["celery_task_id"])

    # 6. Create swarm_consensus_rounds table
    op.create_table(
        "swarm_consensus_rounds",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("swarm_id", sa.String(length=255), nullable=False),
        sa.Column(
            "proposal", postgresql.JSONB(astext_type=sa.Text()), server_default="{}"
        ),
        sa.Column("initiator_agent_id", sa.String(length=255), nullable=True),
        sa.Column(
            "votes", postgresql.JSONB(astext_type=sa.Text()), server_default="[]"
        ),
        sa.Column("result", sa.String(length=50), nullable=True),
        sa.Column("strategy_used", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=True
        ),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["swarm_id"],
            ["swarm_profiles.swarm_id"],
            ondelete="CASCADE",
            name="fk_consensus_rounds_swarm",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_swarm_consensus_rounds"),
    )
    op.create_index("idx_consensus_swarm", "swarm_consensus_rounds", ["swarm_id"])
    op.create_index("idx_consensus_result", "swarm_consensus_rounds", ["result"])

    # 7. Extend agent_communications table with swarm context
    op.add_column(
        "agent_communications",
        sa.Column("swarm_id", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "agent_communications",
        sa.Column(
            "swarm_context", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_index("idx_agent_comm_swarm", "agent_communications", ["swarm_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 7. Revert agent_communications extension (reverse order)
    op.drop_index("idx_agent_comm_swarm", table_name="agent_communications")
    op.drop_column("agent_communications", "swarm_context")
    op.drop_column("agent_communications", "swarm_id")

    # 6. Drop swarm_consensus_rounds (reverse dependency order)
    op.drop_index("idx_consensus_result", table_name="swarm_consensus_rounds")
    op.drop_index("idx_consensus_swarm", table_name="swarm_consensus_rounds")
    op.drop_table("swarm_consensus_rounds")

    # 5. Drop swarm_tasks
    op.drop_index("idx_swarm_tasks_celery", table_name="swarm_tasks")
    op.drop_index("idx_swarm_tasks_status", table_name="swarm_tasks")
    op.drop_index("idx_swarm_tasks_swarm", table_name="swarm_tasks")
    op.drop_table("swarm_tasks")

    # 4. Drop swarm_agents
    op.drop_index("idx_swarm_agents_status", table_name="swarm_agents")
    op.drop_index("idx_swarm_agents_swarm", table_name="swarm_agents")
    op.drop_table("swarm_agents")

    # 3. Drop swarm_profiles
    op.drop_index("idx_swarm_created_by", table_name="swarm_profiles")
    op.drop_index("idx_swarm_status", table_name="swarm_profiles")
    op.drop_table("swarm_profiles")

    # 2. Drop agent_templates
    op.drop_index("idx_agent_templates_rating", table_name="agent_templates")
    op.drop_index("idx_agent_templates_category", table_name="agent_templates")
    op.drop_table("agent_templates")

    # 1. Drop litellm_audit_log
    op.drop_index("idx_litellm_audit_created", table_name="litellm_audit_log")
    op.drop_index("idx_litellm_audit_action", table_name="litellm_audit_log")
    op.drop_index("idx_litellm_audit_user", table_name="litellm_audit_log")
    op.drop_table("litellm_audit_log")

    # ### end Alembic commands ###
