"""add memory_correction_events (D30-60 T29)

Revision ID: 1c2031390969
Revises: f72ba088e872
Create Date: 2026-06-14 13:55:31.634509

Clean hand-written migration. The autogenerated equivalent was full of
pre-existing DB drift noise (unrelated ALTERs on workspace_shares,
workspace_versions, workspaces, etc.). Only the new
memory_correction_events table is created. The pre-existing drift is
tracked in the F1/F4 audit backlog for a separate cleanup migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1c2031390969"
down_revision: Union[str, Sequence[str], None] = ["f72ba088e872", "toolvis_001"]
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Hardcoded tuples — must match app/models/memory_correction_models.py.
ALL_EVENT_TYPES = (
    "view",
    "edit",
    "delete",
    "forget",
    "create",
    "inspect",
    "export",
    "pause",
    "resume",
)
ALL_ACTORS = ("user", "system", "admin")


def upgrade() -> None:
    """Create the memory_correction_events table (D30-60 T29 — privacy audit trail)."""
    op.create_table(
        "memory_correction_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("claim_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("actor", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            f"event_type IN {ALL_EVENT_TYPES}",
            name="ck_memory_correction_event_event_type_valid",
        ),
        sa.CheckConstraint(
            f"actor IN {ALL_ACTORS}",
            name="ck_memory_correction_event_actor_valid",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_memory_correction_events_user_id"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            ondelete="CASCADE",
            name="fk_memory_correction_events_workspace_id",
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["personal_memory_claims.id"],
            ondelete="SET NULL",
            name="fk_memory_correction_events_claim_id",
        ),
        sa.PrimaryKeyConstraint("id", name="memory_correction_events_pkey"),
    )
    op.create_index(
        "ix_memory_correction_events_user_id",
        "memory_correction_events",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_memory_correction_events_workspace_id",
        "memory_correction_events",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_memory_correction_events_claim_id",
        "memory_correction_events",
        ["claim_id"],
        unique=False,
    )
    op.create_index(
        "ix_memory_correction_events_user_ws_created",
        "memory_correction_events",
        ["user_id", "workspace_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_memory_correction_events_user_ws_event_type",
        "memory_correction_events",
        ["user_id", "workspace_id", "event_type"],
        unique=False,
    )


def downgrade() -> None:
    """Drop the memory_correction_events table (D30-60 T29)."""
    op.drop_index(
        "ix_memory_correction_events_user_ws_event_type", table_name="memory_correction_events"
    )
    op.drop_index(
        "ix_memory_correction_events_user_ws_created", table_name="memory_correction_events"
    )
    op.drop_index("ix_memory_correction_events_claim_id", table_name="memory_correction_events")
    op.drop_index(
        "ix_memory_correction_events_workspace_id", table_name="memory_correction_events"
    )
    op.drop_index("ix_memory_correction_events_user_id", table_name="memory_correction_events")
    op.drop_table("memory_correction_events")
