"""add analytics columns to swarm_pipelines

Revision ID: 20249800e422
Revises: 83699f85a14e
Create Date: 2026-04-15 13:17:52.102821

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20249800e422"
down_revision: str | Sequence[str] | None = "83699f85a14e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "swarm_pipelines",
        sa.Column("phase_durations", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("swarm_pipelines", sa.Column("total_duration", sa.Float(), nullable=True))
    op.add_column("swarm_pipelines", sa.Column("task_count", sa.Integer(), nullable=True))
    op.add_column("swarm_pipelines", sa.Column("error_count", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("swarm_pipelines", "error_count")
    op.drop_column("swarm_pipelines", "task_count")
    op.drop_column("swarm_pipelines", "total_duration")
    op.drop_column("swarm_pipelines", "phase_durations")

    # ### end Alembic commands ###
