"""add memory_digest_deliveries (D30-60 T31)

Revision ID: 3959f8d6ee64
Revises: 7d817400002a
Create Date: 2026-06-14 14:05:58.650787

Clean hand-written migration. The autogenerated equivalent was full of
pre-existing DB drift noise (unrelated ALTERs on workspace_shares,
workspace_versions, workspaces, etc.). Only the new
memory_digest_deliveries table is created. The pre-existing drift is
tracked in the F1/F4 audit backlog for a separate cleanup migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3959f8d6ee64"
down_revision: Union[str, Sequence[str], None] = "7d817400002a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Hardcoded tuples — must match app/models/memory_digest_models.py.
ALL_DELIVERY_CHANNELS = ("email", "in_app", "preview")
ALL_DELIVERY_STATUSES = ("pending", "delivered", "failed", "previewed")


def upgrade() -> None:
    """Create the memory_digest_deliveries table (D30-60 T31 — daily digest)."""
    op.create_table(
        "memory_digest_deliveries",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivery_channel", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("claims_count", sa.Integer(), nullable=False),
        sa.Column(
            "claims_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("recipient", sa.String(length=255), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            f"delivery_channel IN {ALL_DELIVERY_CHANNELS}",
            name="ck_memory_digest_delivery_channel_valid",
        ),
        sa.CheckConstraint(
            f"status IN {ALL_DELIVERY_STATUSES}",
            name="ck_memory_digest_delivery_status_valid",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_memory_digest_deliveries_user_id",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            ondelete="CASCADE",
            name="fk_memory_digest_deliveries_workspace_id",
        ),
        sa.PrimaryKeyConstraint("id", name="memory_digest_deliveries_pkey"),
    )
    op.create_index(
        "ix_memory_digest_deliveries_user_id",
        "memory_digest_deliveries",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_memory_digest_deliveries_workspace_id",
        "memory_digest_deliveries",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_memory_digest_deliveries_delivery_channel",
        "memory_digest_deliveries",
        ["delivery_channel"],
        unique=False,
    )
    op.create_index(
        "ix_memory_digest_deliveries_status",
        "memory_digest_deliveries",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_memory_digest_deliveries_user_ws_sent",
        "memory_digest_deliveries",
        ["user_id", "workspace_id", "sent_at"],
        unique=False,
    )
    op.create_index(
        "ix_memory_digest_deliveries_user_ws_channel",
        "memory_digest_deliveries",
        ["user_id", "workspace_id", "delivery_channel"],
        unique=False,
    )
    op.create_index(
        "ix_memory_digest_deliveries_sent_at",
        "memory_digest_deliveries",
        ["sent_at"],
        unique=False,
    )


def downgrade() -> None:
    """Drop the memory_digest_deliveries table (D30-60 T31)."""
    op.drop_index(
        "ix_memory_digest_deliveries_sent_at", table_name="memory_digest_deliveries"
    )
    op.drop_index(
        "ix_memory_digest_deliveries_user_ws_channel",
        table_name="memory_digest_deliveries",
    )
    op.drop_index(
        "ix_memory_digest_deliveries_user_ws_sent",
        table_name="memory_digest_deliveries",
    )
    op.drop_index(
        "ix_memory_digest_deliveries_status", table_name="memory_digest_deliveries"
    )
    op.drop_index(
        "ix_memory_digest_deliveries_delivery_channel",
        table_name="memory_digest_deliveries",
    )
    op.drop_index(
        "ix_memory_digest_deliveries_workspace_id",
        table_name="memory_digest_deliveries",
    )
    op.drop_index(
        "ix_memory_digest_deliveries_user_id", table_name="memory_digest_deliveries"
    )
    op.drop_table("memory_digest_deliveries")
