"""add memory_extraction_pauses (D30-60 T30)

Revision ID: 7d817400002a
Revises: 1c2031390969
Create Date: 2026-06-14 14:01:18.032275

Clean hand-written migration. The autogenerated equivalent was full of
pre-existing DB drift noise (unrelated ALTERs on workspace_shares,
workspace_versions, workspaces, etc.). Only the new
memory_extraction_pauses table is created. The pre-existing drift is
tracked in the F1/F4 audit backlog for a separate cleanup migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7d817400002a"
down_revision: Union[str, Sequence[str], None] = "1c2031390969"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the memory_extraction_pauses table (D30-60 T30 — pause toggle)."""
    op.create_table(
        "memory_extraction_pauses",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=100), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_memory_extraction_pauses_user_id",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            ondelete="CASCADE",
            name="fk_memory_extraction_pauses_workspace_id",
        ),
        sa.PrimaryKeyConstraint(
            "id", name="memory_extraction_pauses_pkey"
        ),
    )
    op.create_index(
        "ix_memory_extraction_pauses_user_id",
        "memory_extraction_pauses",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_memory_extraction_pauses_workspace_id",
        "memory_extraction_pauses",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_memory_extraction_pauses_conversation_id",
        "memory_extraction_pauses",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        "ix_memory_extraction_pauses_lookup",
        "memory_extraction_pauses",
        ["user_id", "workspace_id", "conversation_id", "expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_memory_extraction_pauses_expires_at",
        "memory_extraction_pauses",
        ["expires_at"],
        unique=False,
    )


def downgrade() -> None:
    """Drop the memory_extraction_pauses table (D30-60 T30)."""
    op.drop_index(
        "ix_memory_extraction_pauses_expires_at",
        table_name="memory_extraction_pauses",
    )
    op.drop_index(
        "ix_memory_extraction_pauses_lookup", table_name="memory_extraction_pauses"
    )
    op.drop_index(
        "ix_memory_extraction_pauses_conversation_id",
        table_name="memory_extraction_pauses",
    )
    op.drop_index(
        "ix_memory_extraction_pauses_workspace_id",
        table_name="memory_extraction_pauses",
    )
    op.drop_index(
        "ix_memory_extraction_pauses_user_id", table_name="memory_extraction_pauses"
    )
    op.drop_table("memory_extraction_pauses")
