"""add critiques table (D30-60 T24)

Revision ID: f72ba088e872
Revises: 7a1c2d3e4f5b
Create Date: 2026-06-14 12:40:57.889177

Clean hand-written migration. The autogenerated equivalent was 226KB of
pre-existing DB drift noise (unrelated ALTERs on chat_templates,
swarm_*, workflows, etc.). Only the new critiques table is created.
The pre-existing drift is tracked in the F1/F4 audit backlog for a
separate cleanup migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f72ba088e872"
down_revision: Union[str, Sequence[str], None] = "7a1c2d3e4f5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the critiques table (D30-60 T24 — Critic stack foundation)."""
    op.create_table(
        "critiques",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("mission_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("program_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("critic_kind", sa.String(length=30), nullable=False),
        sa.Column("score_overall", sa.Float(), nullable=True),
        sa.Column("score_alignment", sa.Float(), nullable=True),
        sa.Column("score_safety", sa.Float(), nullable=True),
        sa.Column("score_completeness", sa.Float(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "misses",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "risks",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "improvements",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "alternatives",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("model_id", sa.String(length=100), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "critic_kind IN ('red_team', 'critic', 'improvement_generator')",
            name="ck_critique_critic_kind_valid",
        ),
        sa.CheckConstraint(
            "score_overall IS NULL OR (score_overall >= 0.0 AND score_overall <= 1.0)",
            name="ck_critique_score_overall_range",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_critiques_user_id"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE",
            name="fk_critiques_workspace_id",
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"], ["missions.id"], ondelete="CASCADE",
            name="fk_critiques_mission_id",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"], ["mission_programs.id"], ondelete="CASCADE",
            name="fk_critiques_program_id",
        ),
        sa.PrimaryKeyConstraint("id", name="critiques_pkey"),
    )
    op.create_index(
        "ix_critiques_user_id", "critiques", ["user_id"], unique=False
    )
    op.create_index(
        "ix_critiques_workspace_id", "critiques", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_critiques_mission_id", "critiques", ["mission_id"], unique=False
    )
    op.create_index(
        "ix_critiques_program_id", "critiques", ["program_id"], unique=False
    )
    op.create_index(
        "ix_critiques_critic_kind", "critiques", ["critic_kind"], unique=False
    )
    op.create_index(
        "ix_critiques_user_ws_created",
        "critiques",
        ["user_id", "workspace_id", "created_at"],
        unique=False,
    )


def downgrade() -> None:
    """Drop the critiques table (D30-60 T24 — Critic stack foundation)."""
    op.drop_index("ix_critiques_user_ws_created", table_name="critiques")
    op.drop_index("ix_critiques_critic_kind", table_name="critiques")
    op.drop_index("ix_critiques_program_id", table_name="critiques")
    op.drop_index("ix_critiques_mission_id", table_name="critiques")
    op.drop_index("ix_critiques_workspace_id", table_name="critiques")
    op.drop_index("ix_critiques_user_id", table_name="critiques")
    op.drop_table("critiques")
